version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.1.2-node
      - image: postgres:12
    environment:
      POSTGRES_PASSWORD: your_password # Set the PostgreSQL superuser password
    steps:
      - checkout
      - run:
          name: Update Bundler
          command: gem install bundler
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            until pg_isready -h localhost -p 5432; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            done
      - run:
          name: Set Up Database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
            bundle exec rake db:test:prepare
      - run:
          name: Run Rails Tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: "#e.g. ./deploy.sh"

workflows:
  build-and-test:
    jobs:
      - test-ruby
    # - deploy:
    #     requires:
    #       - test-ruby
