version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.1.2-node
      - image: postgres:12 # Add PostgreSQL service image

jobs:
  test-ruby:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Update Bundler
          command: gem install bundler
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Set Up Database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
            bundle exec rake db:test:prepare
      - run:
          name: Run Rails Tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: "#e.g. ./deploy.sh"

workflows:
  build-and-test:
    jobs:
      - test-ruby
    # - deploy:
    #     requires:
    #       - test-ruby
